name: E2E Tests

on: 
  workflow_dispatch:

jobs:
  E2E_Test: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4'

    - name: Setup jdk 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.6

    - name: Run tests
      run: mvn test -DbrowserType="chrome" -DheadlessExecution="false" -DmaximizeWindow="true" -Dtest="automationexercise.tests.AutomationExerciseTests"

    - name: Publish report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
          name: JEST Tests            # Name of the check run which will be created
          path: target/surefire-reports/TEST-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
        
    
      
      

